---
name: Release

on:
  push:
    tags: [ "v*.*.*" ]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  create-release:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: dist-*
          path: dist
          merge-multiple: true

      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CURRENT_TAG: ${{ github.ref_name }}
        run: |
          LATEST_TAG=$(git tag -l "v*" | sort -V | tail -n 1)

          if [ "${CURRENT_TAG}" = "${LATEST_TAG}" ]; then
            LATEST_FLAG="--latest"
          else
            LATEST_FLAG="--latest=false"
          fi

          if gh release view "${CURRENT_TAG}" >/dev/null 2>&1; then
            echo "Release for ${CURRENT_TAG} already exists. Skipping creation."
          else
            RELEASE_FILES=(dist/*)
            echo "Attaching artifact: ${RELEASE_FILES}"
            gh release create "${CURRENT_TAG}" \
              --title "${CURRENT_TAG}" \
              --generate-notes \
              ${LATEST_FLAG} \
              "${RELEASE_FILES[@]}"
          fi
